"""fix user table

Revision ID: 6b147b397ab4
Revises: feb1386df4fa
Create Date: 2025-10-17 16:11:08.152444

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b147b397ab4'
down_revision = 'feb1386df4fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))
        batch_op.drop_index(batch_op.f('user'))
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', mysql.VARCHAR(length=80), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('user'), ['user'], unique=True)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
