"""empty message

Revision ID: 796a70fa5cd1
Revises: 7d67d07d4d7d
Create Date: 2025-10-18 00:46:33.765814

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '796a70fa5cd1'
down_revision = '7d67d07d4d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
